### ISSUE TITLE
Genetic analyses with GeneClass

### ISSUE THREAD

**Issue by ChloeRN** [ChloeRN/VredfoxIPM#18]
We will re-do the genetic assignment analysis using the software GeneClass. The analysis gives probabilities for each individual to belong to a genetic in-group or out-group (= immigrant) and we are hoping to use this information to constrain the immigration parameter(s) in the IPM. 

We'll run the analysis in 3 ways: 

1. The "naive" way: as done previously, baseline = first year
2. Moving baseline without back-calculation: baseline = foxes harvested during previous 2 years
3. Moving baseline with back-calculation: baseline = foxed harvested during previous 2 years + foxes harvested later but assumed part of population due to age (age > 0)

(In 2. and 3., each fox will be assigned relative to its hypothetical immigration year = birth year, not its harvest year)

There does not seem to be an R interface for GeneClass. The analysis itself will therefore be "external", but code for preparing data for analysis and for preparing outputs for inclusion in the IPM will be part of this repository/workflow. 
There are thus three parts of this task:

- [x] Write function for preparing data for analysis with GeneClass
- [x] Run analyses in GeneClass
- [ ] Write function for reformatting outputs of GeneClass analysis for inclusion in IPM

**Comment by doroehrich** [comment]
After some reconsideration, we decided to run this analysis differently and landed on two variants:
1. Moving base line based on the foxes shot every year. Foxes from one year as assigned to two possible reference populations: Varanger (all foxes shot in the current year and all foxes shot in the two previous years) or the potential source populations (all foxes samples available from Iesjavri, Neiden and Norkynn, independent of the year in which they were shot). 
2. Moving baseline assuming all foxes immigrated in the first year of their life. Here all foxes are classified into cohorts based on their birth year. Then they were assigned to two possible reference populations: Varanger (all foxes from Varanger present in the population in the focal year and the previous year - those shot then a and those present then based on the fact that they were born earlier and shot later) and the potential source populations (all foxes samples available from Iesjavri, Neiden and Norkynn, independent of the year in which they were shot).

As there is no R interface for geneclass, a script was written to make input files for the different geneclass analyses, and another script to read in the result files and assemble them. As we are not updating the genetic data yearly, this part of the analysis will not need to be updated every year. Therefore this script will not be integrated in the main workflow, but stored separately. A table with the results will be an input file for the IPM

**Comment by ChloeRN** [comment]
@doroehrich please add the scripts for dealing with GeneClass inputs and outputs to the repository. We can set up a folder "Auxiliary_Code" for these (and potentially other snippets).

**Comment by doroehrich** [comment]
Hei @ChloeRN, and sorry - but I seem to be to stupid to set up a folder in the repository... Could you please write how to do it or set up one?....

**Comment by ChloeRN** [comment]
@doroehrich there should be one now!
(It's a bit tricky because it only works if there is something in the folder!)

**Comment by doroehrich** [comment]
OK, now it is uploaded. I hope it is OK.
