### ISSUE TITLE
Write genetic data module into IPM

### ISSUE THREAD

**Issue by ChloeRN** [ChloeRN/VredfoxIPM#22]

**Comment by doroehrich** [comment]
We decided to upload this as an independent script in the folder with auxiliary_code, as this is not part of the workflow that will be repeated each yer - that is done

**Comment by ChloeRN** [comment]
I've written two distinct data modules:

1) POOLED GENETIC DATA

- Uses all genetic data to estimate average immigration rate (Mu.immR)
- "Freely" estimates time-variation in immigration rate (sigma.immR)
- Simulates yearly immigration rates (immR[t]) from a lognormal distribution with logmean = log(Mu.immR) and logsd = sigma.immR. 

2) YEARLY GENETIC DATA

- Uses yearly genetic data to estimate yearly immigration rates (immR[t]) for the years with genetic data available
- Calculates average of (Mu.immR) and time-variation in (sigma.immR) immigration rates from estimated immR[t]
- Simulates yearly immigration rates for years without genetic data from a lognormal distribution with logmean = log(Mu.immR) and logsd = sigma.immR. 

(Here, we use individual data to estimate immigration rate in the year in which the fox would have been Age0 / immigrated. This means that we also have data for individuals theoretically immigrated before the first year in the model. We use this data for estimating Mu.immR and sigma.immR as well, but place it in a separate time loop).

**Comment by ChloeRN** [comment]
![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/2b8705fd-315a-4646-99c8-38d58f9cf2bb)

Estimating immigration via a rate gives higher estimates of harvest mortality and lower estimates of other cause mortality. 
It also leads to slightly higher average denning survival. 
The only key vital rate substantially affected by using genetic data is average immigration rate, which becomes much more precise.

**Comment by ChloeRN** [comment]
![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/03f902f3-96e5-4faa-9e33-9d0341cf3eb0)

Modelling immigration as a rate gives more precise estimates of yearly variation in vital rates. 
The total yearly variation in immigration rate is estimated just as well when using pooled genetic data as when not using genetic data at all, but the estimate becomes much lower and more precise when yearly genetic data are used (to little suprise, as it is much more constrained in this case).

**Comment by ChloeRN** [comment]
![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/d39d5bbb-e3b4-4be1-b72c-3864384372f7)
Estimating immigration as a rate gets rid of the issue we had previously with unrealistically large estimates of immigrant numbers (that kept sticking to the upper prior bounds and inflating population size).

**Comment by ChloeRN** [comment]
![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/70a3155b-1e7c-4154-a1d7-a201169e3039)
Consequently, we get substantially lower and more precise estimates of population size when modelling immigration as a rate. 
Using genetic data increases precision of the estimates. 
Notably, when yearly genetic data is used, we further get overall lower estimates of population size.

**Comment by ChloeRN** [comment]
![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/49cf9220-1f86-4903-9709-7487aa069247)
Immigration numbers are more realistic (= lower) when modelling immigration as a rate. The temporal patterns are conserved across approaches, with the only difference being the model with yearly genetic data (here, stronger data constraints alter the pattern somewhat). Precision: numbers < naive rate < rate + pooled data < rate + yearly data

![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/27f33411-433c-4097-aa36-20c61b13a92c)
More or less the same applies for immigration rate.

**Comment by ChloeRN** [comment]
![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/b564de65-f3d0-42ec-8d1d-03fb28878e16)
Finally, we also see that the changes in temporal pattern in immigration rate when using yearly genetic data are mirrored -- to a degree -- in the pattern of recruit numbers.

**Comment by ChloeRN** [comment]
The genetic modules seem to work as they should, and indeed help with the issues we've had before. 
The model with pooled data is a bit more flexible, as it still allows to e.g. model other temporal covariates on immigration rate. It also makes a few less assumptions than the model using yearly genetic data (e.g. does not assume immigration age).

**Comment by ChloeRN** [comment]
Completed via #34
