### ISSUE TITLE
Write data reformatting pipeline to include latest information

### ISSUE THREAD

**Issue by ChloeRN** [ChloeRN/VredfoxIPM#3]
Latest = dissection data from summer 2022

**Comment by ChloeRN** [comment]
We are missing the link between the data format as provided by @doroehrich previously and the data format as implemented in the COAT database.

**Comment by ChloeRN** [comment]
We'll establish the formal link to the database at a later point since updates are still being made and there are some access issues.

**Comment by doroehrich** [comment]
The data base is updated until the hunting season 2021-2022 now. So all data should be available
