### ISSUE TITLE
Reindeer carcass scenario rodent-cycle dependent

### ISSUE THREAD

**Issue by stijnhofhuis** [ChloeRN/VredfoxIPM#59]
In our earlier model version we found that reindeer carcass numbers and rodent numbers might interact, and positively affect red fox survival.
 
Henden et al. 2009 writes:
•        In populations with pronounced resource driven multi-annual population cycles, the effect of management actions could be expected to be "cyclic phase-dependent".  
•        Much can be gained by targeting management action to moments in time when the population is most responsive to any given action.  
•        A general recommendation to be derived from the present study is that management programs should be run as continuously as possible, but with the highest intensity allocated to phases of the demographic cycle in which the population is most prone to respond to management action. 
 
So: Depending on which vital rates drive population growth during different parts of the rodent cycle (LTRE results), management actions that target these vital rates should be implemented during these corresponding phases of the cycle. 
In our example we already test this with the higher hunting mortality during different phases of the rodent cycle. Our thinking being that during certain parts of the small rodent phase, the vital rate of survival is of increased importance, and  hunting could then reduce survival even further (perhaps assuming no compensatory mortality)
 
But thinking about our reindeer carcass scenario, I believe the 2 scenarios we now considered were 1) a max threshold of carcasses, and 2) a % decrease in carcasses.
Given our finding however that reindeer carcasses might be especially important for red fox survival during rodent low years  Would it not be more interesting to have a scenario in which we reduce reindeer carcasses only in rodent low years. This would fit very well with the recommendations of Henden et al. 2009 since we expect survival to be an important vital rate during rodent low years and reindeer carcass availability affects survival to a greater extent during that time.
 
I also think that in practical management terms this could be a realistically implemented scenario since for example reindeer herders would only have to remove reindeer from varanger during some winters, e.g. varanger would not be a vinterbeite area during rodent-low years, but in rodent high years it would be oke.
 
In terms of coding, I suppose this scenario would be similar to the “increased hunting during rodent-low” scenario?

Taking this idea even further we could also have a scenario where we increase both hunting and remove reindeer during rodent low years for double impact, but I suppose that this is too much for now so maybe we can just discuss that option the discussion.

My vision would be to end up with a graph that shows 4 lines of population development

-	Reindeer mortality stays the same
-	Reindeer mortality reduced by 50% in all years
-	Reindeer mortality reduced by 50% in low rodent years   (= more cost effective than in all years, with perhaps the same effect)
-	Reindeer mortality reduced by 50% in high rodent years (= to show the difference between doing it in low years)

I am curious to hear doro's opinion on this

**Comment by stijnhofhuis** [comment]
But maybe I can use your help here Doro, what do you think is the most realistic in terms of what reindeer herders or other management people can do: 1) reduce reindeer mortality by a certain % each year, or 2) prevent peak mortality by making sure reindeer mortality is below a certain threshold each year? 
I guess this question comes down to this: 1)Would it be realistic from a reindeer herder perspective or management (e.g. removal efforts) to for example remove 50% of all carcasses each year? OR  2) Are peak mortality years caused by specific management decisions such as leaving reindeer in Varanger in winter, in other words would it be realistic to prevent peak mortality by some sort of management change / decision?
 
If mortality is accidental (e.g. weather), and we imagine management to come more down to removing carcasses afterwards rather than preventing mortality, I suppose a % reduction is more realistic. If peak mortality is somewhat due to human decision making which can be prevented, maybe removing those peaks would be a more realistic scenario.
 
And then maybe a 3rd question for Chloe, is one of them easier to model than the other?
 
Depending on what you think, I image different options for the reindeer mortality scenarios:
 
1:
 
•	Reindeer mortality stays the same
•	Reindeer mortality reduced by 50% in all years
•	Reindeer mortality reduced by 50% in low rodent years
•	Reindeer mortality reduced by 50% in high rodent years (perhaps just to show the difference between doing it in low years)
 
2: 
•	Reindeer mortality stays the same
•	Reindeer mortality cannot be higher than the mean of the data we have
•	Reindeer mortality cannot be higher than the mean in low rodent years
•	Reindeer mortality cannot be higher than the mean in high rodent years (perhaps just to show the difference between doing it in low years)
 
 
My understanding of the situation is that mortality is mostly due to weather, so accidental in some sense, so perhaps a % reduction (physically removing carcasses afterwards) is more realistic. So I would vote for this, also because it seems easier to explain. But please let me know if you have something to add to this.

**Comment by stijnhofhuis** [comment]
Chloe writes:
I have code I can build on to make a percent decrease. 
We do not have the resources to develop yet another set of scenarios using thresholds. 
Of course we can consider mentioning that alternative in the discussion, but we are not modelling thresholds this time.

**Comment by doroehrich** [comment]
Hei Stijn and Chloe,

Some of this we should probably discuss with reindeer herders themselves. If Frank Inge shows up at the reference meeting, we could maybe talk to him a little.

But my understanding is that of course reindeer owners want to reduce reindeer mortality as much as possible. If many reindeer die, this is usually understood as the result of bad weather conditions (together maybe with not optimal management decisions). Also I am not sure how much the variation in the moving the reindeer out of Varanger in winter is a planned decision and how much of it happens because the herders did not succeed to move out the reindeer as they wanted.

Also realistically I don’t think the herders would consider changing their management because of the role carcasses play for red foxes (but I did not talk to them about it, it would be interesting to talk for instance with Jan Ivvar Smuk about it maybe). But I assume they want to adapt their management as good as possible to the varying winter conditions in order to maximize condition, survival and calf production. So I don’t think a scenario where reindeer mortality gets modified depending on the small rodent cycle is particularly realistic – but it can still be interesting theoretically in context of our model to make clear the interaction between these two main resources.

Concerning removing carcasses after the reindeer died, I also don’t know how realistic this is and whether this is something the herders would consider. But this is something which could clearly be suggested as a management action.

That are probably my not very clear thoughts about this.

Best,
Dorothee

**Comment by stijnhofhuis** [comment]
Oke thanks for your thoughts Doro!
It makes sense that reindeer owners would want to reduce reindeer mortality as much as possible regardless. In that sense I suppose that indeed management actions to reduce mortality further might be unrealistic. Perhaps in that sense carcass removal (after the fact) is the most realistic alternative if we want to have a scenario with reduced reindeer carcasses.

In that case, where carcass removal is the management action that the reindeer scenario is about, I think it woul dbe interesting to see if we should remove carcasses in all years, or can get similar results with just removing carcasses in rodent low years.

**Comment by doroehrich** [comment]
Hello both,

Regarding the reindeer and the reduction of mortality: I think a mortality reduction scenario could still be interesting – that would assume that owners manage to adapt better to the new climatic conditions, predict better where there will be food, or improve supplemental feeding. That could reduce average mortality or probably mostly reduce variance/prevent mortality peaks.

But yes, I agree, a scenario removing reindeer carcasses in rodent low years could also be interesting.

Best,
Doro

**Comment by ChloeRN** [comment]
Shelving this as we won't implement this now.
