### ISSUE TITLE
Ideas about rodents..

### ISSUE THREAD

**Issue by stijnhofhuis** [ChloeRN/VredfoxIPM#66]
Hi Chloe and Doro,

Apologies for breaking Chloe’s ”no new ideas” rule again haha. Somehow I can’t help myself. I’m just going to write down my idea here and we can see if we want to pick it up at some point.

So the rodent abundance index we came up with where we normalised for the seasons (because much more rodents are caught in autumn so we don’t want spring to become “overshadowed”), and for species, (because voles are easier to catch and we don’t want lemming to become “overshadowed”), is a pretty complicated approach. And I am not entirely sure what the reviewers would think about it. After talking to Eivind about it he also has some doubts about it, because it is fair to normalise data multiple times? And are we not overcomplicating things?
So with that in the back of my head for a while and the fact that Chloe and I fixed some indexing mistakes which caused the rodent x reindeer interaction to become a bit unexpected, I could help myself but take another look at how and why we decided to make the rodent variable the way we did.
Most of it was decided on the basis of these plots, where we see that rodent data treated by standardizing (or normalizing is perhaps the better word) ( “cont.wintvar.stsp”) fluctuates quite nicely with the % of breeding foxes in orange and the mean litter size in red. Now the plot here is for adults only, I did this because I thought that adding juveniles would mess up the correlation a bit because they get less pups and are less often pregnant, and in some years you might have more juveniles.
 

![1111](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/b5aecfbd-4b89-4c7a-9e5a-939e4f40311f)

 
Now what you see here is that sometimes the red (litter size) and orange (% pregnant) fall a bit behind eachother. I was a bit confused by that and thought maybe its because there is not so much data if you exclude all juveniles. So then I added the juveniles and surprise the lag becomes even bigger:

 
![1112](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/e0bbc1e2-fd9f-4e4b-ae7e-6d4f0cd10f3a)

So here I find it quite difficult to understand why it would be so. I have 2 theories. 
1) Let’s say you’re a fox that managed to get a territory and is fit enough to breed. From those breeding foxes perspective’s, I suppose it makes sense not to invest too much in a litter right after a peak (red curve is lowest then) because your offspring will have pretty bad chances for the future. In practical terms it might mean resorption of some embryos towards the end of the pregnancy once the fox gets in a bad conditions or realise that there will be few rodents that spring. Just before a peak however, your off spring will have pretty good chances so then it is perhaps good to have higher litter sizes. Thus explaining the red curve.
Now from an “any fox” perspective, this fluctuates more clearly with the actual rodent number of that particular winter. From an “any fox” perspective, the resources of the moment perhaps explains better whether you would be able to breed at all. Perhaps explaining why the orange (%breeding) follows the rodent cycle better.

2 )Now theory 2) is that this pattern is driven by the age structure of the population. We know that younger foxes have lower litter sizes (see image below), so after a peak there are lots of young foxes, driving down the average litter size. Just before the next peak the population is quite old, meaning high litter sizes. During the peak litter sizes are still quite high, but in some cases the influx of new pups from the year before when rodents were on the increase reduced the average litter size already in the peak year.

![1113](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/e275f678-cf89-4f7e-9035-6f581ff7879e)

 

When it comes to % breeding, young foxes also show less likelihood to breed, so I’m not entirely sure why % breeding would not follow the same pattern as nr. of pups if the age structure of the population is what causes this pattern. Perhaps resources are so high in the peak years that most of the pups breed aswell? Albeit with lower litter sizes?
My question here is whether we should discuss this, is it important to how we match reproduction with rodent in the model? Or if its just an artefact of the data (theory 2), will the model deal with this fine because it anyway predicts different litter sizes for different age classes?
To me the pattern looks so predictable that its almost a shame not to show you / discuss it. 
What makes me doubt a bit the idea that this pattern is entirely driven by the age structure of the population, (which the model would then deal with, knowing the age structure) is that when we look at the model results the relationship between litter size and rodentAbundance is perhaps not as clear as this red curve seems to indicate:
 
![1114](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/eeaa805f-1dd2-4b81-859b-9137b9bf973a)

Oke so that is one question I have, the other one is whether using this complicated rodent variable is necessarily better than another one. I realised that instead of using such a line to capture the yearly dynamics of rodent and reproductive values I could also just plot the two against eachother in a scatterplot. This gives this result for the complicated rodent variable that normalizes voles and lemmings separately:
![1116](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/3e8a12ec-fd30-4cd0-9853-5cd5609dbe7d)

 

So here we see a pretty oke relationship between the rodent variable on the x axis and %pregnant on the left and mean litter sizes on the right. (for all foxes)
Ims et al. 2017 found that arctic fox litter sizes in Varanger had a clear relationship with lemming abundances but not so much with vole abundance. Killengreen et al. 2011 also found the red foxes ate mostly lemmings in winter and not so much voles. Although I think later data that Doro has also shows some vole consumption. So below I made the same plots for lemming abundance in winter instead of the more complicated rodent calculation:
 
![1117](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/52d5b568-26e8-462a-84be-82d8adf3cc50)

Perhaps similar or almost better results? So I wonder if we think that the rodent variable is unnecessarily complicated we could just go for lemming instead?

**Comment by ChloeRN** [comment]
In my opinion, covariates should be chosen / designed with a biological hypothesis and some practical considerations in mind and not as a (sole) result of "pattern-searching" in raw data that we know to be subject to a variety of biases. 
With a biological hypothesis, we have a solid, well founded reason to expect an effect of a a covariate on our quantity of interest. We also a priori define what we believe to be the mechanism behind this relationship (based on our best knowledge of the biology of species). 
If we do "pattern searching" instead and aim to optimize a covariate for maximum covariation with the quantity of interest, we may estimate a higher and possibly more precise effect but this can come at the cost of the biological explanation. If we chase a pattern (or correlation), and the hypothesis about the mechanism behind the relationship comes AFTER the estimation, there is a real risk of getting lost in trying to find explanations for a pattern that may well be the result of very complex interactions we may not even be aware of. 
So if we were to entertain the idea of other versions of a rodent covariate and/or different time indexing for these covariates, I'd suggest that this be based on what we know about the biology of rodents and foxes and their ecosystem, NOT on the premise that we want to maximize fit to a pattern in the raw data.

**Comment by ChloeRN** [comment]
A few additional thought: 

You say that "when we look at the model results the relationship between litter size and rodentAbundance is perhaps not as clear as this red curve seems to indicate". I beg to differ. Given all the constraints and the (somewhat limited) degree of statistical power we have in this model, that is a pretty solid positive relationship between rodent abundance and litter size. 

Also, have a look at this: 
![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/8ee0a04d-3e84-41f1-83e7-2fbcd9abdc19)

This is the comparison of a model using the covariate with species weights (red) and without (blue). We get more precise estimates using the weights but overall the estimates are quite similar (and they do not really affect anything beyond the rodent effect estimates in the model.
What I want to say with this is that I would be very surprised if slight alterations to the rodent covariate would change anything noteworthy in the model. I think we really are at the limit of what we can expect to get out of a model with the data we have now, and a slightly different covariate here or there is not gonna affect that at all.

**Comment by stijnhofhuis** [comment]
Just to finish off this story and for future reference:
I had a look and this pattern we see here where litter sizes go up in the year before the rodent peak:

![289673445-e0bbc1e2-fd9f-4e4b-ae7e-6d4f0cd10f3a](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/e954acd1-a52a-4911-9aff-87d41fb914c9)

Is indeed because of the age structure in the population. Just before the peak th epopulation is quite old, and older individuals get more pups. During higher rodent all age classes still get more pups, but there are also more juveniles during that time, evening it out a little bit in relation to just before the peak when the population was old

**Comment by stijnhofhuis** [comment]
To complete the rodent story further;
In my memory we did not discuss so much the possibility of using stomach content data to infer rodent abundance and their use by foxes in different years. One could argue that the stomach content data is a reflection of a foxes perspective on the rodent situation that takes into account preference between different species. This could be an alternative to doing this species weighing that we did. Although probably this comes with its own biases (theoretically, i dont mean that we should do this).

If someone is going to use this code for modeling another hunted population of mesopredators, perhaps for which little enviromental data is available, using stomach content data to infer fluctuations in environment might be an option

Here stomach content data of our foxes that Doro prepared: You can see similar rodent fluctuations as in our data, more lemmings seem to be caught by foxes than by our traps


![Picture2](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/e4c0b12e-32fd-4118-a130-ec261a5983a1)

**Comment by stijnhofhuis** [comment]
A (fun) observation: As i was looking at the estimates for natural mortality over time, I was comparing the natural mortality estimates to our small rodent abundance. To see how important rodent is for that.

It matches quite well, in years with low small rodent abundance, there is higher natural mortality. See below

![natmortyears](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/fa12be5d-3d55-47d1-8c4e-1da22c462307)

![rod and natmort](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/c9fdbe35-3eb4-4d21-a2d6-34c62ad91c3a)

The only year it doesnt really match is 2018, i wondered why so had a look at summer harvest. 

![Skjermbilde 2023-12-15 111445](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/fb29ca19-b9c2-4be5-80ae-4a57d4dccdf3)

Turns out in 2018 there was relatively alot of summer harvest, which probably the model doesnt know because we only used data until 2012 for summer harvest. So I suppose that is why the model thinks natural mortality in 2018 was so high, but it was actually harvest :) Maybe also part of the reason the rodent effect on natural mortality is not super clear

Not saying we should change anything, Chloe tried incorporating the known number of harvest in summer without age structure for the later years, but this gave some weird results, trying to read up again on what those were

**Comment by stijnhofhuis** [comment]
Oke so see Issue 48 for when Chloe tried this.

One of the issues when chloe tried this was this:
![image](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/aa6cdf3c-38b5-426a-b55d-51693fcfb177)

I think my only remaining question is this: Is this "issue" likely to have been caused by the wrong time indexing on rodent with natural mortality that we used then, or does this have nothing to do with it?
If so will it make any difference trying this again with the right rodent time indexing on natural mortality? 

I'm not saying that we should do this as I know there is no time left, just trying to understand the model output a bit and the different option /decison points that have led to our current result. And I wonder how imprtant this part could be where we get summer harvest more "correct" thereby potentially getting natural mortality more "correct", and thereby understanding the role of rodents better.

**Comment by ChloeRN** [comment]
> To complete the rodent story further; In my memory we did not discuss so much the possibility of using stomach content data to infer rodent abundance and their use by foxes in different years. One could argue that the stomach content data is a reflection of a foxes perspective on the rodent situation that takes into account preference between different species. This could be an alternative to doing this species weighing that we did. Although probably this comes with its own biases (theoretically, i dont mean that we should do this).
> 
> If someone is going to use this code for modeling another hunted population of mesopredators, perhaps for which little enviromental data is available, using stomach content data to infer fluctuations in environment might be an option
> 
> Here stomach content data of our foxes that Doro prepared: You can see similar rodent fluctuations as in our data, more lemmings seem to be caught by foxes than by our traps
> 
> ![Picture2](https://private-user-images.githubusercontent.com/119519700/290786795-e4c0b12e-32fd-4118-a130-ec261a5983a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzgwMjgsIm5iZiI6MTcwMjYzNzcyOCwicGF0aCI6Ii8xMTk1MTk3MDAvMjkwNzg2Nzk1LWU0YzBiMTJlLTMyZmQtNDExOC1hMTMwLWVjMjYxYTU5ODNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMDU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2E5MGVkMWNmOGJjOGNjNWYyN2YzN2QxODVhZmI0ZmRhNjFhN2Y0MGY0NGVkYjc1Zjc2OThmM2NlM2M4ZmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tL7RmoIDG7Cl9s0FsIL3e1KLeNl9_fiVHxhqJr6io1o)

I agree that using the stomach contents could give a slightly different perspective. However, this data too will have its own suite of biases, and there is one more reason why monitored rodent abundance may be "more useful": management (i.e. harvesting) could be adapted according to monitored and/or predicted rodent abundance. This is not really possible for rodents in stomachs as a covariate, as that information does not become available until after the necropsies (which is AFTER the relevant hunting season).

**Comment by stijnhofhuis** [comment]
Sounds good @ChloeRN!
By the way I think I posted / edited the comment above about  this summer harvest in 2018 question while you were replying to the other comment, so I'd just like to check if you saw it or not :)
I promise its my last question :D
Best

**Comment by ChloeRN** [comment]
I'm trying to answer/wrap up remaining questions here. 
So, about higher natural mortality in years with low rodent abundance: we are kind of "forcing" that by fitting an effect of rodent abundance on natural mortality and constraining it to be negative. So no big surprise here. 
The high summer harvest in 2018 is definitely "bleeding into" natural mortality here. It was substantially higher than what the model would predict based on the data for 2005-2012, so the "extra" will have slipped into natural mortality. I also do not think that this will change now that we have "fixed" the rodent indexing. If anything, the change gave us a less precise estimate of the rodent effect. So all in all, I think for now we will have to live with knowing that we have an understimation of summer harvest mortality and consequent overestimation of natural mortality in 2018.
