### ISSUE TITLE
link litter size observations SNO hunt to placental scars of mom directly?

### ISSUE THREAD

**Issue by stijnhofhuis** [ChloeRN/VredfoxIPM#68]
Hi , just a small question, since we have this litter size estimates of red foxes when SNO went and shot all the pups on the den 4 times (and 6 estimates from cameras on afox dens). I'm wondering if we have placental scar data from the mom, would that make the mortality estimates more accurate because we know exactly how mant pups died in betwene pregnancy and den appearance for that particular fox mom?

**Comment by ChloeRN** [comment]
@stijnhofhuis with a sample size of 4 (at best), this is highly unlikely to make a difference for the model. Statistical power is just too low, so I don't think there is any point in pursuing this at present. But might be worth revisiting if that particular dataset keeps growing.
